name: dadban
description: "اپلیکیشن مدیریت دفتر وکالت دادبان"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  permission_handler: ^11.3.1
  record: ^5.1.2
  just_audio: ^0.9.36
  google_mlkit_text_recognition: ^0.13.0
  speech_to_text: ^6.6.0
  table_calendar: ^3.1.1
  shamsi_date: ^1.0.1
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1

flutter:
  uses-material-design: true

